Minor errors to get notebook running
NASA-PDS/pds-api-notebook pull request #1
Opened 2021-06-29 20:54 UTC by al-niessner

2021-06-29 20:57 UTC, al-niessner commented
@tloubrieu-jpl 

Please review and merge. Seems to be working for me now.

2021-07-14 17:08 UTC, jordanpadams commented
@tloubrieu-jpl is this still a WIP? or are we good to merge?

2021-07-14 17:12 UTC, tloubrieu-jpl commented
@al-niessner can you look at my comments on the pull request. No a big deal but that will allow to merge the pull request. Thanks.

2021-07-14 17:14 UTC, tloubrieu-jpl requested changes

2021-07-14 17:14 UTC, tloubrieu-jpl commented
@jordanpadams ok, I missed to complete the review. That is done now.

2021-07-14 17:46 UTC, al-niessner commented on requirements.txt
> +ipywidgets
done

2021-07-14 18:42 UTC, nutjob4life approved these changes
Fine with me; 🚢 it.

2021-07-15 18:39 UTC, tloubrieu-jpl approved these changes

2021-07-15 18:39 UTC, merged